[package]
name = "john-wick-parse"
version = "0.2.1"
authors = ["Waddlesworth <github@genj.io>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
hex = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
image ="0.21"